git:
  submodules: false

if: branch = master AND type != pull_request

install:
  - git checkout -B master origin/master

  - openssl aes-256-cbc -K $encrypted_caaf7cb5c9ab_key -iv $encrypted_caaf7cb5c9ab_iv -in ssh/id_ecdsa.enc -out ~/.ssh/id_ecdsa -d
  - chmod 600 ~/.ssh/id_ecdsa
  - ssh-keyscan 'github.com' 'aur.archlinux.org' >> ~/.ssh/known_hosts

  - gpg --keyserver hkps://pgp.mit.edu --recv-keys 14F26682D0916CDD81E37B6D61B7B526D98F0353

  - git config --global user.email 'jat@sinosky.org'
  - git config --global user.name 'Jat'
  - git remote set-url origin git@github.com:jat001/aur-firefox-developer.git

jobs:
  include:
    - stage: update
      before_script: '[[ "$(git log -1 --pretty=%B)" == *"[force update]"* ]] && [ "$TRAVIS_EVENT_TYPE" == "push" ] && args="-f" || :'
      script: ./update.sh "$args"

    - stage: add
      script: ./add.sh
