git:
  submodules: false

install:
  - '[ "$TRAVIS_BRANCH" == master ] || travis_terminate 0'
  - git checkout -B master origin/master

  - openssl aes-256-cbc -K $encrypted_caaf7cb5c9ab_key -iv $encrypted_caaf7cb5c9ab_iv -in ssh/id_ecdsa.enc -out ~/.ssh/id_ecdsa -d
  - chmod 600 ~/.ssh/id_ecdsa
  - ssh-keyscan 'github.com' 'aur.archlinux.org' >> ~/.ssh/known_hosts

  - git config --global user.email 'jat@sinosky.org'
  - git config --global user.name 'Jat'
  - git remote set-url origin git@github.com:jat001/aur-firefox-developer.git

script:
  - ./update.sh
  - ./add.sh
