git:
  submodules: false

install:
  - '[ "$TRAVIS_BRANCH" == master ] || travis_terminate 0'
  - rm -rf "$TRAVIS_BUILD_DIR"
  - git clone -b master 'git@github.com:jat001/aur-firefox-developer.git' "$TRAVIS_BUILD_DIR"

  - git config --global user.email 'jat@sinosky.org'
  - git config --global user.name 'Jat'
  - git checkout master

  - openssl aes-256-cbc -K $encrypted_caaf7cb5c9ab_key -iv $encrypted_caaf7cb5c9ab_iv -in ssh/id_ecdsa.enc -out ~/.ssh/id_ecdsa -d
  - chmod 600 ~/.ssh/id_ecdsa
  - ssh-keyscan 'aur.archlinux.org' >> ~/.ssh/known_hosts

script:
  - ./update.sh
